### ISSUE TITLE
Error on Ubuntu 20.04

### ISSUE THREAD

**Issue by MandiYang** [iwoithe/Pug#1]
When running python3 -i main.py:
```
Traceback (most recent call last):
  File "main.py", line 179, in <module>
    pug = PugWindow()
  File "main.py", line 53, in __init__
    self.setup_ui()
  File "main.py", line 57, in setup_ui
    self.add_docks()
  File "main.py", line 66, in add_docks
    self.uninstall = Uninstall(parent=self)
  File "/home/mandi/Downloads/Pug-master/src/Pug/ui/docks/uninstall/uninstall.py", line 39, in __init__
    self.packages_model = QStringListModel(self.get_packages())
  File "/home/mandi/Downloads/Pug-master/src/Pug/ui/docks/uninstall/uninstall.py", line 85, in get_packages
    package_name, package_version = package.split("==")
ValueError: not enough values to unpack (expected 2, got 1)
>>> 
```
Python3 version: python3.8

**Comment by iwoithe** [comment]
Hi @MandiYang,

Does [this](https://github.com/iwoithe/Pug/commit/14d38eeaf4fd9e1ad2d1968ceed53727c81d37b6) commit fix this issue?

**Comment by MandiYang** [comment]
Yes, tx
